accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import signup

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),
]

ticket_manager/urls.py
from django.urls import path

from ticket_manager import views

urlpatterns = [
    path('', views.base, name='home'),
    path('tickets/', views.tickets, name='tickets'),
    path('tickets/add', views.add_ticket, name='add_ticket'),
    path('tickets/id=<id>', views.ticket, name='ticket'),
    path('tickets/id=<id>/edit', views.edit_ticket, name='edit_ticket'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),  # /login, /logout, /signup
    path('', include('ticket_manager.urls')),  # /, /tickets, /tickets/id=<id>, /tickets/add, /tickets/id=<id>/edit
]

ticket_manager/models/comment.py
from django.db import models
from .ticket import Ticket


class Comment(models.Model):
    ticket = models.ForeignKey(
        to=Ticket,
        on_delete=models.CASCADE,
        related_name='comment'
    )

    content = models.TextField(
        null=False
    )

    @classmethod
    def create(cls, ticket, content):
        return cls(ticket=ticket, content=content)

    class Meta:
        app_label = 'ticket_manager'
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

ticket_manager/models/ticket.py
from enum import Enum

from django.db import models
from django.contrib.auth.models import User
from django_enum_choices.fields import EnumChoiceField


class TicketStatus(Enum):
    OPEN = 'open'
    CLOSED = 'closed'


class Ticket(models.Model):
    worker = models.ForeignKey(
        to=User,
        limit_choices_to={'groups__name': "workers"},
        on_delete=models.CASCADE,
    )

    status = EnumChoiceField(
        enum_class=TicketStatus,
        default=TicketStatus.OPEN
    )

    description = models.CharField(
        max_length=511,
        null=False,
    )

    details = models.TextField(
        null=False
    )

    @classmethod
    def close_ticket(cls, id):
        return cls.objects.filter(id=id).update(status=TicketStatus.CLOSED)

    @classmethod
    def create(cls, worker, description, details):
        return cls(worker=worker, description=description, details=details)

    def update(self, worker, description, details):
        self.worker = worker
        self.description = description
        self.details = details
        return self.save()

    def __str__(self):
        return self.description[:100] + '...'

    class Meta:
        app_label = 'ticket_manager'
        verbose_name = 'ticket'
        verbose_name_plural = 'tickets'

accounts/forms/signup.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    pass

    class Meta:
        model = User
        fields = ('username', 'groups', 'password1', 'password2')

ticket_manager/forms/comment.py
from django import forms

class CommentForm(forms.Form):
    comment = forms.CharField()

ticket_manager/forms/ticket.py
from django.forms import ModelForm

from ticket_manager.models import Ticket


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['worker', 'description', 'details']

accounts/views/signup.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group

from accounts.forms import SignUpForm


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user.groups.add(form.cleaned_data.get('groups').first())
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

ticket_manager/views/add_ticket.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from ticket_manager.forms import TicketForm
from ticket_manager.models import Ticket
from website.errors import raise_403


def add_ticket(request):
    if request.user.has_perm('ticket_manager.add_ticket'):
        if request.method == 'GET':
            form = TicketForm()

            context = {
                'form': form
            }

            return render(
                request,
                'add_ticket.html',
                context
            )

        elif request.method == 'POST':
            form = TicketForm(request.POST)
            if form.is_valid():
                Ticket.create(
                    worker=User.objects.filter(id=form.data['worker']).first(),
                    description=form.data['description'],
                    details=form.data['details']
                ).save()
                return redirect('tickets')
    else:
        return raise_403()

ticket_manager/views/base.py
from django.shortcuts import render, redirect

def base(request):
    if request.method == 'GET':

        if request.user.is_authenticated:
            return redirect('tickets')
        else:
            return render(
                request,
                'base.html',
            )

ticket_manager/views/edit_ticket.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from ticket_manager.forms import TicketForm
from ticket_manager.models import Ticket
from website.errors import raise_403


def edit_ticket(request, id):
    ticket = Ticket.objects.filter(id=id).first()
    if request.user.has_perm('ticket_manager.change_ticket'):
        if request.method == 'GET':
            form = TicketForm(initial={
                'worker': ticket.worker,
                'description': ticket.description,
                'details': ticket.details
            })

            context = {
                'form': form
            }

            return render(
                request,
                'edit_ticket.html',
                context
            )

        elif request.method == 'POST':
            form = TicketForm(request.POST)
            if form.is_valid():
                ticket.update(
                    worker=User.objects.filter(id=form.data['worker']).first(),
                    description=form.data['description'],
                    details=form.data['details']
                )
                return redirect('ticket', id)
            print(form)
    else:
        return raise_403()

ticket_manager/views/ticket.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from ticket_manager.forms import CommentForm
from ticket_manager.models import Ticket, Comment
from website.errors import raise_403


def ticket(request, id):
    ticket = Ticket.objects.filter(id=id).first()
    current_user = request.user

    if not (current_user.groups.filter(name='managers').exists() or current_user == ticket.worker):
        return raise_403()  # 403 in cases of non-manager or ticket worker login

    if request.method == 'GET':
        form = CommentForm()

        context = {
            'ticket': ticket,
            'comment': Comment.objects.filter(ticket=ticket).first(),
            'form': form
        }

        return render(
            request,
            'ticket.html',
            context
        )

    elif request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            Comment.create(
                ticket=ticket,
                content=form.data['comment']
            ).save()
            ticket.close_ticket(ticket.id)
        return HttpResponseRedirect(request.path_info)  # redirect to self

ticket_manager/views/tickets.py
from django.shortcuts import render

from ticket_manager.models import Ticket
from website.errors import raise_403


def tickets(request):
    if request.method == 'GET':

        current_user = request.user
        if current_user.groups.filter(name='managers').exists():
            tickets = Ticket.objects.all()
        elif current_user.groups.filter(name='workers').exists():
            tickets = Ticket.objects.filter(worker=current_user)
        else:
            return raise_403()

        context = {
            'tickets': tickets,
        }

        return render(
            request,
            'tickets.html',
            context
        )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Management</title>
    <STYLE type="text/css">
        H2 {text-align: center}
    </STYLE>

</head>
<body>

{% block navbar %}
    {% if not user.is_authenticated %}
            You are not logged in! <br>
            <a href=//{{ request.META.HTTP_HOST }}/login/>login</a>
            <a href=//{{ request.META.HTTP_HOST }}/signup/>signup</a>
    {% else %}
            You are logged in as {{ request.user.username }} <br>
            <a href=//{{ request.META.HTTP_HOST }}/logout/>logout</a> <br>
    {% endif %}
{% endblock %}

{% block content %}
{% endblock %}

</body>
</html>

ticket_manager/templates/add_ticket.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

ticket_manager/templates/edit_ticket.html
{% extends 'base.html' %}

{% block content %}
{#    {% if perms.ticket_manager.edit_ticket %}#}
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Save changes</button>
        </form>
{#    {% endif %}#}
{% endblock %}

ticket_manager/templates/ticket.html
{% extends "base.html" %}

{% block content %}

    <h2>{{ticket.description}}: {{ticket.status.value}}</h2>

    {% if perms.ticket_manager.change_ticket and ticket.status.value == 'open' %}
        <a href="//{{ request.META.HTTP_HOST }}/tickets/id={{ ticket.id }}/edit">
            <button><p>Edit ticket</p></button>
        </a>
    {% endif %}

    <p>
        <b>status:</b> {{ticket.status.value}} <br>
        <b>worker:</b> {{ ticket.worker }} <br>
        <b>description:</b> {{ticket.description}} <br>
        <b>detais:</b> {{ ticket.details }}
    </p>

    {% if ticket.status.value == 'open' %}
        {% if perms.ticket_manager.add_comment %}
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Post</button>
            </form>
        {% endif %}
    {% else %}
        <b>comment:</b> {{ comment.content }}<br>
    {% endif %}

    <a href="//{{ request.META.HTTP_HOST }}/tickets/">Return</a>

{% endblock %}

ticket_manager/templates/tickets.html
{% extends "base.html" %}

{% block content %}

    <h2>Tickets:</h2>
    <ul>
        {% for ticket in tickets %}
        <li>
            <a href="//{{ request.META.HTTP_HOST }}/tickets/id={{ ticket.id }}">
                <button><p>
                    status: {{ticket.status.value}} <br>
                    description: {{ticket.description}} <br>
                    worker: {{ ticket.worker }} <br>
                </p></button>
            </a>
        </li>
        {% endfor %}
    </ul>

    {% if perms.ticket_manager.add_ticket %}
        <a href="//{{ request.META.HTTP_HOST }}/tickets/add">
            <button><p>+ New Ticket</p></button>
        </a><br>
    {% endif %}

{% endblock %}